### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by rocherroche**

### CODE REVIEW

**Comment by yihming** [comment]
In `pegasus_analysis.ipynb`:
* Resolve the weird double-stars appearing along with the content in red:
Screen Shot 2022-03-02 at 17 05 24
  If you cannot make the content both in red and in bold, then making it just in red is okay.
* Correct the two references (I highlighted them in red circles):
issue-2
* Which version of `umap-learn` was installed in the conda environment running this notebook? If it's not v0.5.2, please upgrade it to this version and rerun the notebook.
* In the line below, change name from `"result.zarr.zip"` to `"MantonBM_result.zarr.zip"` to be consistent with the other notebooks, and remove the inline comment:
Screen Shot 2022-03-02 at 17 22 03

**Comment by yihming** [comment]
In `plotting_tutorial.ipynb`:
* Remove the lines in red highlight block. The `gender` attribute should already exist in the input data:
Screen Shot 2022-03-02 at 17 27 14

**Comment by yihming** [comment]
In `doublet_detection.ipynb`:
* Why does it have the following lines at the end of the file? Looks like a cached output. You may need to rerun the notebook to remove it.
Screen Shot 2022-03-02 at 17 39 19

**Comment by yihming** [comment]
In `batch_correction.ipynb`:
* Correct the description paragraph below the performance plot to make it consistent with the plot:
Screen Shot 2022-03-03 at 00 04 09

**Review by yihming — CHANGES_REQUESTED** [review]
Please see my comments regarding different notebooks.

**Comment by yihming** [comment]
In `regress_out.ipynb`:
* No Line 4. You need to rerun the notebook to correct the line numbering.

**Comment by rocherroche** [comment]
> In `pegasus_analysis.ipynb`:
> 
> * Resolve the weird double-stars appearing along with the content in red:
> 
> Screen Shot 2022-03-02 at 17 05 24
> 
> If you cannot make the content both in red and in bold, then making it just in red is okay. * Correct the two references (I highlighted them in red circles):
> issue-2
> 
> * Which version of `umap-learn` was installed in the conda environment running this notebook? If it's not v0.5.2, please upgrade it to this version and rerun the notebook. * In the line below, change name from `"result.zarr.zip"` to `"MantonBM_result.zarr.zip"` to be consistent with the other notebooks, and remove the inline comment:
> Screen Shot 2022-03-02 at 17 22 03

(jupyter_pegasus) rocherr@rocherr-RKML7L pegasus % pip list| grep umap          
umap-learn            0.5.2

**Pull request closed without merging**
