### PR TITLE
speed up calculate_auc_values()

### PR DESCRIPTION
**Pull request by slowkow**
As mentioned in issue #15, the code for AUROC can be more efficient.

This commit improves the calculate_auc_values() function so that it runs
more quickly:

    145k cells, 28k genes, and 23 clusters
    Before: 1044 seconds running on 8 threads
    After:   325 seconds running on 1 thread

Before, the code was using parallel processing to repeat redundant
calculations independently for each cluster.

After, the code uses a single thread and does fewer redundant
calculations.

To reduce the complexity of the algorithm, I deleted the part
that deals with `cond_labels`, but it can be added back in.

To do:
- [x] Add support for `cond_labels` again.
- [x] Learn from the [presto] R package how to run 10 times more efficiently.

[presto]: https://github.com/immunogenomics/presto

More details
------------

The underlying idea is that some intermediate values can be computed
once, saved, and then reused multiple times.

For example, it is necessary to sort and rank each gene to compute the
AUROC and the Wilcoxon rank sum test p-value.

It is inefficient to sort and rank each gene N times for N clusters.

A more efficient approach is to sort and rank each gene once. Then,
those ranks can be accessed multiple times to compute the statistics for
N clusters.

### CODE REVIEW

**Comment by yihming** [comment]
I tested Kamil's modification on MantonBM_nonmix dataset on my macOS. It took 598.04s in AUC step, comparing with Pegasus 8-thread's 1833.88s. And the result in `adata.varm['de_res']` remains the same.

The command-line tool doesn't need to support `condition` argument, but interactive API needs it.

**Comment by slowkow** [comment]
I made one more change in cef9fb8 and now the time is down from 325 to 138 seconds.

**Comment by slowkow** [comment]
I believe the Python code is now as efficient as the presto R package code. I brought the time down from 138 to 27 seconds.

Regarding the `condition` argument, I have a question. Is it true that the purpose of this argument is to answer the question:

- Is expression predictive of a binary vector within each cluster?

If that is true, then it seems to me that we can run the new AUROC code separately on each expression matrix that corresponds to each cluster. This should be a fast way to support the `condition` argument.

Could I please ask if this is the right interpretation?

**Comment by slowkow** [comment]
OK, I think I'm finished working on this pull request. I would be delighted to hear your comments.

I believe this new code should work just the same way as the original before my pull request, but it is much faster.

We might consider another version in the future where we use the U statistics computed in this code to get the MWU p-values. (The same U statistic is used to compute the AUROC and also to compute the Mann-Whitney U test p-value.)

On my data with 145k cells, 28k genes, and 23 clusters:
- 27 seconds for regular AUROC
- 58 seconds for conditional AUROC within each cluster

**Comment by bli25** [comment]
Hi Kamil,

Thanks so much for working on this. I'll take a look and merge it into
Pegasus this week.

Thanks,
Bo

Bo Li, Ph.D.
Director, Bioinformatics and Computational Biology Program, Center for
Immunology and Inflammatory Diseases, Massachusetts General Hospital
Member of the Faculty, Harvard Medical School
Associated Scientist, Klarman Cell Observatory, Broad Institute of MIT &
Harvard
149 13th Street, Room 8214, Charlestown, MA 02129

**Comment by slowkow** [comment]
Hi Bo,

It seems like we might want to activate some tests so we automatically know that the pull request does not break anything.

Let me know if you need help to get the tests up and running again.

(Anyway, I already tested this code, so it would be surprising to me if it fails any tests.)

**Comment by slowkow** [comment]
Just to clear up a bit of confusion...

pegasus depends on GPL packages:

- https://pypi.org/project/louvain/
- https://pypi.org/project/python-igraph/
- https://pypi.org/project/forceatlas2-python/

So, it seems like it might have been reasonable to make a python package that is a translation of the [presto](https://github.com/immunogenomics/presto) R package, and then add that as a dependency.

Anyway, I guess this isn't relevant anymore, considering that the differential expression analysis code has been updated in pegasus 1.0.0.

---

By the way, I think it is OK for a BSD package to depend on a GPL package.

For example, matplotlib (custom BSD-like [license](https://github.com/matplotlib/matplotlib/blob/master/LICENSE/LICENSE)) depends on [PyQT4](https://pypi.org/project/PyQt4/) (GPL):

https://github.com/matplotlib/matplotlib/blob/dbae370733f2bfd7b616bf1972294a2eff020747/lib/matplotlib/backends/qt_compat.py#L116

**Pull request closed without merging**
